import { Blog } from "../interfaces/blog";

export const blog_content: Blog[] = [
    {imageUrl: "https://source.unsplash.com/z4_MYkk6JoM/480x360",title:'Amazing Experience in Water park',content:'An awesome opportunity awaits you at the Water Park! Come and explore all the exciting rides, amusing games, and much more!',date:'April 30, 2021'},
    {imageUrl: "https://source.unsplash.com/z6IBhEySkso/480x360",title:'Enjoy the Natural Beauty of Water Park',content:'Revel in the gorgeous scenery at the Water Park. Go for a stroll and appreciate the loveliness of the outdoors.',date:'May 19, 2021'},
    {imageUrl: "https://media.istockphoto.com/id/1331782413/photo/happy-family-with-inflatable-toys-in-swimming-pool-at-water-park.jpg?b=1&s=170667a&w=0&k=20&c=1ewBKJG9q4fsWS-sB54uFGiSxF8CsHmOvK7z16GD3PQ=",title:'A Family Friendly Water Park',content:'Make unforgettable memories with your loved ones at the Water Park. You can find lots of thrilling adventures that are appropriate for everyone. Devote a day of enjoyment with your family at the Water Park!',date:'May 22, 2021'},
    {imageUrl: "https://media.istockphoto.com/id/1383593039/photo/two-multiracial-couples-conversing-on-pool-deck.jpg?b=1&s=170667a&w=0&k=20&c=6Oh4jWDMZXfl5rc42pa_Ip1gctHagVKZynwUBOHv5-4=",title:'A Trip to the Water Park',content:'Last weekend, I had an amazing experience at the water park. From the thrilling slides to the large lazy river, there was no shortage of entertaining activities. The most memorable moment was taking a boat tour around the park, allowing me to observe its magnificence from the water.',date:'June 7, 2021'},
    {imageUrl: "https://media.istockphoto.com/id/540205990/photo/mother-baby-girl-swim-and-dive-underwater-in-pool.jpg?b=1&s=170667a&w=0&k=20&c=y6pY83L2SoO-YIK31N36XsVv-uD2GxQmXofKHFztp40=",title:'The Joy of Swimming',content:'I had an unforgettable time at the water park while swimming. Everywhere I looked there were people having a blast, and I was no exception. The soothing water made it even more enjoyable, and I even met some interesting people during my time there. We had a lot of fun laughing and playing in the pool.',date:'June 19, 2021'},
    {imageUrl: "https://media.istockphoto.com/id/959106344/photo/wonderful-blue-and-bright-ripple-water-and-surface-in-swimming-pool-beautiful-motion-gentle.jpg?b=1&s=170667a&w=0&k=20&c=a8tYqavHXk74E1G--1Jnm6ppGZVgQfyPlff3Sn6Ys_I=",title:'A Magical Place',content:'I experienced a feeling of enchantment when I went to the water park. Everywhere I gazed, there were vibrant shades and cheerful countenances. It was delightful to just relax and observe the magnificence of nature encompassing me.',date:'August 17, 2021'},

]
